name: reusable Workflow
on:
 workflow_call:
   inputs:
     name: 
       description: "Input Description"
       type: string
       default: 'DINESH'
       required: false
   secrets: 
      access-token: 
        description: secret description
        required: true

jobs: 
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -a
  
  log-context-and-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ inputs.name }}'
      - run: echo '${{ secrets.access-token }}'    

